name: PostgreSQL Service Example
on:
  workflow_dispatch:
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: |
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432
    steps:
      - run: pg_isready -h localhost -p ${{job.services.postgres.ports[5432]}}
      - run: ech "Run tests against Postgre"
