name: sample-download-artifacts
run-name: ${{ github.actor }} download a log artifacts
on:
  workflow_dispatch:
jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
